### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by 3rd-Eden** [primus/primus#51]
Primus has grown into a framework we can all depend upon in our daily lives. It is and will always be an innovative way to work and build real-time applications.
### Feature & API freeze

The base of Primus is feature complete. Additional logic and features can easily be added on top of Primus through the plugin interface. The only features that might be added in the future would be those that improve the connectivity and stability of Primus or an enhancement of the currently available methods. One of these features might be:
- [ ] Port degrading or upgrading for WebSocket connections.
- [ ] Upgrading and downgrading between transformers using 1 single JS file.
### New transformers

Transformers are the most important part about Primus. They are the engines that Primus rides upon. We're currently supporting some of the most popular real-time frameworks:
- Engine.IO
- Socket.IO
- SockJS
- WebSockets
- Browserchannel

But there a lot more frameworks and transports available that we're not yet supporting. In the future we should add support for:
- [ ] [simpleio](https://github.com/kof/simpleio)
- [ ] [websocket emulation](https://github.com/gimite/web-socket-js) -- also known as flashsockets.
- [x] [faye-websocket](https://github.com/faye/faye-websocket-node)

With the addition of Flashsockets we should also start supporting them in:
- [ ] Engine.IO
- [ ] Socket.IO

As they've been disabled because of the engineering overhead it takes to get this running smoothly. Currently all real-time systems require you to use your own Node.js powered real-time server. The ultimate goal for this project is to prevent lock-in, this includes lock-in from Node.js. In order to support that we can add support for lightstreamer. They provide a node.js module to interact with their services so in addition to the 2 transformers listed above, we should start with integrating cloud solutions:
- [ ] https://github.com/Weswit/Lightstreamer-lib-node-adapter
### Better static support

Serving files from the `/primus` pathname is really convenient, we should optimize our file serving and make it easier to add files. Which is needed for serving the flash files and additional libraries for the FlashSocket transport.
### Tests

There is nothing more important in this project then tests. While we have great coverage already, we can still improve this. I've setup a sauselabs account so we can have automated browser testing. We've tried using testling before, but it failed misserably and because it's build on browserify, the stacktraces and the error feedback that you get from it is completely useless. So this needs to addressed
- [ ] Run client tests on saus labs
- [ ] Write more tests for the clients
- [ ] Write even more tests
- [ ] Write integration tests
### Website

We've purchased the `primus.io` domain name, we should add a proper website with documentation and API references for the client, spark and server interface as wel as a list of `primus` modules.
- [ ] Run the application @nodejitsu
- [ ] Design a website
- [ ] Add API reference material
- [ ] Add another working demo of Primus.
